"""Expose and compare fingerprints already generated by the V1 FingerprintEngine."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Iterable

from v2.modules.fingerprint_engine.models import FingerprintChange, FingerprintReport


_DIMENSIONS = ("security", "networking", "identity", "governance", "logging", "overall")


def build_fingerprint_report(snapshots: Iterable[dict[str, Any]]) -> FingerprintReport | None:
    """Return the latest valid V1 fingerprint and changes from its predecessor.

    The score/hash generation remains exclusively in ``sr.engines.fingerprint_engine``.
    This module only reads persisted V1 results and compares them.
    """

    fingerprinted = [snapshot for snapshot in snapshots if _fingerprint(snapshot) is not None]
    if not fingerprinted:
        return None

    current = fingerprinted[-1]
    current_fingerprint = _fingerprint(current) or {}
    previous_fingerprint = _fingerprint(fingerprinted[-2]) if len(fingerprinted) > 1 else None
    return FingerprintReport(
        timestamp=_timestamp(current) or datetime.min,
        architecture=_string(current_fingerprint.get("architecture")),
        overall_score=_number(current_fingerprint.get("overall")),
        hash_value=_string(current_fingerprint.get("hash")),
        changes=tuple(_compare(previous_fingerprint, current_fingerprint)),
    )


def _compare(previous: dict[str, Any] | None, current: dict[str, Any]) -> list[FingerprintChange]:
    if previous is None:
        return []

    changes: list[FingerprintChange] = []
    for dimension in _DIMENSIONS:
        old_value = previous.get(dimension)
        new_value = current.get(dimension)
        if old_value != new_value:
            changes.append(
                FingerprintChange(
                    dimension=dimension.replace("_", " ").title(),
                    previous=_display(old_value),
                    current=_display(new_value),
                )
            )

    if previous.get("architecture") != current.get("architecture"):
        changes.append(
            FingerprintChange(
                dimension="Architecture rating",
                previous=_display(previous.get("architecture")),
                current=_display(current.get("architecture")),
            )
        )
    return changes


def _fingerprint(snapshot: dict[str, Any]) -> dict[str, Any] | None:
    value = snapshot.get("fingerprint")
    return value if isinstance(value, dict) else None


def _timestamp(snapshot: dict[str, Any]) -> datetime | None:
    value = snapshot.get("timestamp")
    if not isinstance(value, str):
        return None
    for pattern in ("%Y-%m-%d_%H-%M-%S", "%Y-%m-%dT%H:%M:%S"):
        try:
            return datetime.strptime(value, pattern)
        except ValueError:
            continue
    return None


def _number(value: Any) -> float | None:
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _string(value: Any) -> str | None:
    return str(value) if value is not None else None


def _display(value: Any) -> str:
    return f"{value:.1f}" if isinstance(value, float) else str(value) if value is not None else "N/A"
