"""On-demand Bedrock storytelling panel for historical assessments."""

from __future__ import annotations

from collections.abc import Callable
import re

import streamlit as st

from sr.services.contracts import CapabilityStatus


BEDROCK_MODEL_ID = "eu.amazon.nova-2-lite-v1:0"
ESTIMATED_INPUT_TOKENS = 600
ESTIMATED_OUTPUT_TOKENS = 400
TOKEN_CONFIRMATION_THRESHOLD = 5_000
# Informational preview rates only; regional Bedrock pricing may differ.
ESTIMATED_INPUT_COST_PER_1K_USD = 0.0003
ESTIMATED_OUTPUT_COST_PER_1K_USD = 0.0025


def render_ai_storytelling(
    status: CapabilityStatus,
    generate_demo_story: Callable[[], str],
    generate_ai_story: Callable[[], str],
) -> None:
    """Render local and Bedrock-backed storytelling without exposing infrastructure."""

    st.subheader("AI Storytelling")
    st.caption("Compare real historical snapshots using local mode or Amazon Bedrock.")

    if not status.available:
        st.info("Nessuna narrativa disponibile. Esegui almeno due assessment per generare una cronologia.")
        return

    mode = st.radio("Narrative mode", ["Demo — Local Mode", "AI — Amazon Bedrock"], horizontal=True)
    using_bedrock = mode.startswith("AI")
    if using_bedrock:
        _render_bedrock_estimator()
    else:
        _render_local_mode_card()

    requires_confirmation = using_bedrock and _total_estimated_tokens() > TOKEN_CONFIRMATION_THRESHOLD
    confirmed = True
    if requires_confirmation:
        st.warning(f"Estimated usage exceeds {TOKEN_CONFIRMATION_THRESHOLD:,} tokens.")
        confirmed = st.checkbox("I confirm the estimated Amazon Bedrock consumption.", key="confirm_bedrock_estimate")

    if st.button(
        "Generate historical narrative",
        type="primary",
        key="generate_ai_story",
        disabled=using_bedrock and not confirmed,
    ):
        try:
            with st.spinner("Generating evidence-based narrative..."):
                # Both modes return text into the current Streamlit session. No links,
                # browser navigation, or client-side page-opening code is involved.
                if using_bedrock:
                    st.session_state["v2_ai_story"] = generate_ai_story()
                else:
                    st.session_state["v2_ai_story"] = generate_demo_story()
                st.session_state["v2_ai_story_mode"] = "Bedrock" if using_bedrock else "Local"
        except Exception as error:
            st.error(f"Bedrock storytelling unavailable: {error}")

    story = st.session_state.get("v2_ai_story")
    if story:
        with st.container(border=True):
            story_mode = st.session_state.get("v2_ai_story_mode", "Unknown")
            st.caption(f"Generated by: {story_mode}")
            st.markdown("#### Historical narrative")
            if story_mode == "Local":
                st.markdown(_safe_local_markdown(story), unsafe_allow_html=False)
            else:
                st.markdown(story)


def _render_local_mode_card() -> None:
    with st.container(border=True):
        st.markdown("**Local Mode**")
        st.markdown("✓ Nessuna chiamata Bedrock  \n✓ Consumo token: 0  \n✓ Costo stimato: $0.00")


def _render_bedrock_estimator() -> None:
    input_cost = ESTIMATED_INPUT_TOKENS / 1_000 * ESTIMATED_INPUT_COST_PER_1K_USD
    output_cost = ESTIMATED_OUTPUT_TOKENS / 1_000 * ESTIMATED_OUTPUT_COST_PER_1K_USD
    total_cost = input_cost + output_cost
    risk_label, risk_method = _risk_indicator(_total_estimated_tokens())

    with st.container(border=True):
        st.markdown("**Amazon Bedrock — Token & Cost Estimator**")
        left, middle, right = st.columns(3)
        with left:
            st.caption("Selected model")
            st.code(BEDROCK_MODEL_ID)
            st.caption(f"Input tokens: ~{ESTIMATED_INPUT_TOKENS:,}")
        with middle:
            st.caption(f"Output tokens: ~{ESTIMATED_OUTPUT_TOKENS:,}")
            st.caption(f"Total tokens: ~{_total_estimated_tokens():,}")
            st.caption(f"Estimated AWS cost: ~${total_cost:.4f}")
        with right:
            risk_method(f"Consumption risk: {risk_label}")
            st.caption("Informational preview; verify regional AWS pricing before production use.")


def _total_estimated_tokens() -> int:
    return ESTIMATED_INPUT_TOKENS + ESTIMATED_OUTPUT_TOKENS


def _risk_indicator(total_tokens: int) -> tuple[str, Callable[[str], None]]:
    if total_tokens > TOKEN_CONFIRMATION_THRESHOLD:
        return "High", st.error
    if total_tokens > TOKEN_CONFIRMATION_THRESHOLD // 2:
        return "Medium", st.warning
    return "Low", st.success


def _safe_local_markdown(story: str) -> str:
    """Preserve Markdown presentation while neutralizing navigable local content."""

    without_markdown_links = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", story)
    return without_markdown_links.replace("https://", "hxxps://").replace("http://", "hxxp://")
