"""On-demand storytelling panel for historical assessments."""

from __future__ import annotations

from collections.abc import Callable

import streamlit as st

from sr.services.contracts import CapabilityStatus


def render_ai_storytelling(
    status: CapabilityStatus,
    generate_demo_story: Callable[[], str],
    generate_ai_story: Callable[[], str],
) -> None:
    """Render local and Bedrock-backed storytelling in the current dashboard."""

    st.subheader("AI Storytelling")
    st.caption("Compare real historical snapshots using local mode or Amazon Bedrock.")

    if not status.available:
        st.info("Nessuna narrativa disponibile. Esegui almeno due assessment per generare una cronologia.")
        return

    mode = st.radio(
        "Narrative mode",
        ["Demo — Local Mode", "AI — Amazon Bedrock"],
        horizontal=True,
    )
    using_bedrock = mode.startswith("AI")

    if using_bedrock:
        st.warning("Amazon Bedrock will be used for this request.")
    else:
        st.success(
            "Local Mode\n\n"
            "• No Bedrock calls\n\n"
            "• Token consumption: 0\n\n"
            "• Estimated cost: $0.00"
        )

    if st.button("Generate historical narrative", type="primary", key="generate_ai_story"):
        try:
            with st.spinner("Generating evidence-based narrative..."):
                if using_bedrock:
                    story = generate_ai_story()
                    story_mode = "Bedrock"
                else:
                    story = generate_demo_story()
                    story_mode = "Local"

                st.session_state["v2_ai_story"] = story
                st.session_state["v2_ai_story_mode"] = story_mode
        except Exception as error:
            st.error(f"Bedrock storytelling unavailable: {error}")

    story = st.session_state.get("v2_ai_story")
    if story:
        with st.container(border=True):
            story_mode = st.session_state.get("v2_ai_story_mode", "Unknown")
            st.caption(f"Generated by: {story_mode}")
            st.markdown("#### Historical narrative")
            st.markdown(story, unsafe_allow_html=False)
