"""Presentation component for persisted V1 Landing Zone fingerprints."""

from __future__ import annotations

import streamlit as st

from v2.modules.fingerprint_engine.models import FingerprintReport


def render_fingerprint(report: FingerprintReport | None) -> None:
    """Render current fingerprint and its actual historical changes."""

    st.subheader("Landing Zone Fingerprint")
    st.caption("Generated by the V1 Fingerprint Engine and compared across history snapshots.")
    if report is None:
        st.info("No V1 fingerprint is available in the current history.")
        return

    rating, score = st.columns(2)
    with rating:
        st.metric("Architecture Rating", report.architecture or "N/A", border=True)
    with score:
        value = f"{report.overall_score:.1f}/100" if report.overall_score is not None else "N/A"
        st.metric("Overall Score", value, border=True)

    if report.hash_value:
        st.caption("Current V1 SHA-256 fingerprint")
        st.code(_short_hash(report.hash_value))

    if not report.changes:
        st.caption("No changes detected against the previous fingerprinted snapshot.")
        return

    st.markdown("**Main fingerprint changes**")
    for change in report.changes:
        st.write(f"• {change.dimension}: {change.previous} → {change.current}")


def _short_hash(value: str) -> str:
    return value if len(value) <= 32 else f"{value[:16]}…{value[-16:]}"
